# This is a basic workflow to help you get started with Actions

name: Auto Update

on:
  push:
    branches: '**'
    tags: '**'
  schedule:
    - cron: '* * * * *'

jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - name: install
      run: |
        gem install bundler
        bundle install
        npm ci
        git submodule update --init
    - name: Update BCDice
      run: |
        git checkout -f origin/master
      working-directory: BCDice
    - name: Build
      run: npm run build
    - name: Test
      run: |
        npm run test
        npm run example
